---
# http://about.travis-ci.org/docs/user/getting-started/

rvm:
  - 1.8.7
  - 1.9.3

before_script:
  - "bundle install"

script:
  - "rake spec"

# http://about.travis-ci.org/docs/user/build-configuration/#Set-environment-variables
env:
  - PUPPET_VER='~> 3.0' FACTER_VER='~> 2.0'
  - PUPPET_VER=2.7.22 FACTER_VER='<= 1.7.2'

matrix:
  allow_failures:
    - env:
      - PUPPET_VERSION=2.7.21

# http://about.travis-ci.org/docs/user/notifications/#Email-notifications
notifications:
  email: false
